name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:

    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1

    - name: Install
      run: npm install esbuild

    - name: Build
      run: npm run-script build

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Deno Compile
      run: |
          deno compile --allow-all -o build/hsd-cli bundle/hsd-cli.js
          deno compile --allow-all  -o build/hsw-cli bundle/hsw-cli.js

    - name: Prepare Package
      run: |
        mkdir -p pkg/usr/bin
        cp -r debian/ pkg/
        cp build/hsd-cli pkg/usr/bin
        cp build/hsw-cli pkg/usr/bin
        cp bin/hsd-rpc pkg/usr/bin
        cp bin/hsw-rpc pkg/usr/bin
    - name: Publish PPA
      uses: yuezk/publish-ppa-package@main
      with:
        repository: 'ppa:pcfreak30/hns-cli'
        gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
        pkgdir: '${{ github.workspace }}/pkg'
