name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:

    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1

    - name: Install
      run: npm install esbuild

    - name: Build
      run: npm run-script build

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Deno Compile
      run: |
          deno compile --allow-all -o build/hsd-cli bundle/hsd-cli.js
          deno compile --allow-all  -o build/hsw-cli bundle/hsw-cli.js

    - name: Prepare Package
      run: |
        NAME=$(cat package.json | jq -r '.name')
        VERSION=$(cat package.json | jq -r '.version')
        PKG_FOLDER="$NAME-$VERSION"
        mkdir -p $NAME-$VERSION/usr/bin
        cp -r debian/ $PKG_FOLDER/
        cp build/hsd-cli $PKG_FOLDER/usr/bin
        cp build/hsw-cli $PKG_FOLDER/usr/bin
        cp bin/hsd-rpc $PKG_FOLDER/usr/bin
        cp bin/hsw-rpc $PKG_FOLDER/usr/bin
        echo "PKG_FOLDER=$PKG_FOLDER" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Publish PPA
      run: |
          echo '{"fqdn": "ppa.launchpad.net", method:"sftp", "incoming": "~'"$GITHUB_REPOSITORY_OWNER"'/ubuntu/'"$(basename $GITHUB_REPOSITORY)"'/", "allow_unsigned_uploads": 0}'
          sudo apt-get install gpg debmake debhelper devscripts distro-info-data distro-info -y
          for DISTRO in "$(distro-info --supported)"; do
              GPG_KEY_ID=$(echo "$GPG_PRIVATE_KEY" | gpg --import-options show-only --import | sed -n '2s/^\s*//p')
              debmake -n
              rm -f $PKG_FOLDER/debian/changelog
              dch --create -D bionic -M --package "hns-cli" --newversion "$VERSION"  --empty
              echo "y" | debuild -S -sa \
                          -k"$GPG_KEY_ID" \
                          -p"gpg --batch --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback"
              debsign -k$GPG_KEY_ID *.changes
              dput ppa.launchpad.net *.changes
          done

      env:
          GPG_PRIVATE_KEY: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
